import { useRef, useState } from 'react';
import type { FormEvent } from 'react';
import { Camera, Check, Mic, Plus, Trash2, X } from 'lucide-react';
import { useFamily } from '../store';
import { dateKey, datetimeInput, uid } from '../domain';
import type { FamilyEvent, Member, Slot } from '../domain';
import { Avatar, ErrorMessage, Field, Panel, Submit } from './shared';

type Props = { close: () => void; done: (message: string) => void };
export function CourseForm({ close, done, memberId }: Props & { memberId: string }) {
  const { data, dispatch, busy } = useFamily(); const [error, setError] = useState(''); const [times, setTimes] = useState(['08:00']);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { await dispatch({ type: 'course', value: { id: uid(), memberId: String(f.get('member')), name: String(f.get('name')).trim(), strength: String(f.get('strength')).trim(), amount: Number(f.get('amount')), unit: String(f.get('unit')), startDate: String(f.get('start')), days: Number(f.get('days')), times, instructions: String(f.get('instructions')) } }); done('Medicine course added. Your schedule is ready.'); } catch (e) { setError((e as Error).message); } }
  return <Panel title="A little care, planned." subtitle="Copy the dose and timing from the medicine instructions. We’ll keep track of the schedule." back={close}><form onSubmit={submit} className="form-stack"><Field label="Who is it for?"><select name="member" defaultValue={memberId || data.members[0]?.id}>{data.members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Medicine name"><input name="name" placeholder="Name on the label" required maxLength={100}/></Field><Field label="Strength" hint="For example, the concentration printed on the bottle or packet."><input name="strength" placeholder="Copy exactly from the label" required maxLength={80}/></Field><div className="two-col"><Field label="Amount per dose"><input name="amount" type="number" min="0.001" step="any" required placeholder="Amount"/></Field><Field label="Unit"><select name="unit"><option>ml</option><option>tablet(s)</option><option>capsule(s)</option><option>drop(s)</option><option>puff(s)</option><option>sachet(s)</option><option>mg</option></select></Field></div><div className="two-col"><Field label="First day"><input name="start" type="date" defaultValue={dateKey()} required/></Field><Field label="Number of days"><input name="days" type="number" min="1" max="90" defaultValue="4" required/></Field></div><fieldset><legend>Dose times</legend><p className="hint">Choose the actual times you intend to give it. Times follow this device’s timezone.</p><div className="time-inputs">{times.map((time, i) => <div className="time-input" key={i}><input aria-label={`Dose time ${i + 1}`} type="time" required value={time} onChange={e => setTimes(times.map((t, j) => j === i ? e.target.value : t))}/>{times.length > 1 && <button type="button" className="icon-button" aria-label={`Remove time ${i + 1}`} onClick={() => setTimes(times.filter((_, j) => j !== i))}><X size={16}/></button>}</div>)}</div>{times.length < 8 && <button className="text-button" type="button" onClick={() => setTimes([...times, ''])}><Plus size={16}/> Add a time</button>}</fieldset><Field label="Instructions or notes (optional)"><textarea name="instructions" rows={3} maxLength={1000} placeholder="Anything you want both parents to remember"/></Field><div className="notice">This creates reminders, not a prescription. Check the details before saving.</div><ErrorMessage message={error}/><Submit busy={busy}>Create medicine schedule</Submit></form></Panel>;
}
export function DoseForm({ slot, close, done, recorder }: Props & { slot: Slot; recorder: string }) {
  const { data, dispatch, busy } = useFamily(); const [error, setError] = useState(''); const [status, setStatus] = useState<'given' | 'skipped'>('given'); const member = data.members.find(m => m.id === slot.course.memberId)!;
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { await dispatch({ type: 'dose', value: { id: uid(), courseId: slot.course.id, slot: slot.key, actualAt: new Date(String(f.get('time'))).toISOString(), recordedAt: new Date().toISOString(), by: String(f.get('by')), amount: Number(f.get('amount')), unit: slot.course.unit, status, note: String(f.get('note')) } }); done(status === 'given' ? 'Dose recorded. One less thing to remember.' : 'Skipped dose recorded.'); } catch (e) { setError((e as Error).message); } }
  return <Panel title="Log a dose" subtitle="A clear record, for both of you." back={close}><div className="selected-person"><Avatar member={member}/><div><strong>{member.name}</strong><span>Scheduled {new Date(slot.key).toLocaleString([], { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}</span></div></div><div className="medicine-summary"><strong>{slot.course.name}</strong><span>{slot.course.strength} · {slot.course.amount} {slot.course.unit} scheduled</span>{slot.course.instructions && <p>{slot.course.instructions}</p>}</div><form onSubmit={submit} className="form-stack"><div className="segmented" aria-label="Dose status"><button type="button" aria-pressed={status === 'given'} className={status === 'given' ? 'active' : ''} onClick={() => setStatus('given')}>Given</button><button type="button" aria-pressed={status === 'skipped'} className={status === 'skipped' ? 'active' : ''} onClick={() => setStatus('skipped')}>Skipped</button></div><div className="two-col"><Field label={status === 'given' ? `Amount given (${slot.course.unit})` : 'Scheduled amount'}><input name="amount" type="number" min="0.001" step="any" defaultValue={slot.course.amount} readOnly={status === 'skipped'} required/></Field><Field label="Recorded by"><select name="by" defaultValue={recorder}>{data.members.filter(m => m.role === 'parent').map(m => <option key={m.id}>{m.name}</option>)}</select></Field></div><Field label={status === 'given' ? 'When was it given?' : 'When was it skipped?'}><input name="time" type="datetime-local" defaultValue={datetimeInput()} max={datetimeInput(new Date(Date.now() + 60000))} required/></Field><Field label={status === 'skipped' ? 'Reason for skipping' : 'Note (optional)'}><textarea name="note" rows={3} required={status === 'skipped'} maxLength={1000} placeholder={status === 'skipped' ? 'What happened?' : 'Anything worth remembering?'}/></Field><ErrorMessage message={error}/><Submit busy={busy}><Check size={18}/> {status === 'given' ? 'Confirm dose given' : 'Confirm skipped dose'}</Submit><p className="hint centered">Only confirm after the dose has actually been given or skipped.</p></form></Panel>;
}
export function EventForm({ close, done, initial }: Props & { initial?: FamilyEvent }) {
  const { data, dispatch, busy } = useFamily(); const [error, setError] = useState('');
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { await dispatch({ type: 'event', value: { id: initial?.id ?? uid(), title: String(f.get('title')), startsAt: new Date(String(f.get('start'))).toISOString(), endsAt: new Date(String(f.get('end'))).toISOString(), memberIds: f.getAll('members').map(String), category: String(f.get('category')) as FamilyEvent['category'], location: String(f.get('location')), notes: String(f.get('notes')) } }); done('Family event saved.'); } catch (e) { setError((e as Error).message); } }
  return <Panel title={initial ? 'Edit your plan' : 'Something to look forward to.'} subtitle="School days, little adventures, and everything in between." back={close}><form className="form-stack" onSubmit={submit}><Field label="What’s happening?"><input name="title" required defaultValue={initial?.title} placeholder="School trip, play date, holiday…" maxLength={120}/></Field><Field label="Category"><select name="category" defaultValue={initial?.category ?? 'family'}><option value="family">Family</option><option value="school">School</option><option value="play">Play date</option><option value="appointment">Appointment</option></select></Field><Field label="Starts"><input type="datetime-local" name="start" defaultValue={datetimeInput(initial ? new Date(initial.startsAt) : new Date())} required/></Field><Field label="Ends"><input type="datetime-local" name="end" defaultValue={datetimeInput(initial ? new Date(initial.endsAt) : new Date(Date.now() + 3600000))} required/></Field><fieldset><legend>Who’s going?</legend><div className="check-members">{data.members.map(m => <label key={m.id}><input type="checkbox" name="members" value={m.id} defaultChecked={initial?.memberIds.includes(m.id)}/><Avatar member={m} small/>{m.name}</label>)}</div></fieldset><Field label="Where (optional)"><input name="location" defaultValue={initial?.location} maxLength={200} placeholder="Add a place"/></Field><Field label="Notes (optional)"><textarea name="notes" defaultValue={initial?.notes} maxLength={2000} rows={3} placeholder="Pack a lunch, bring swimming kit…"/></Field><ErrorMessage message={error}/><Submit busy={busy}>Save event</Submit></form></Panel>;
}
export function MemberForm({ member, close, done }: Props & { member: Member }) {
  const { dispatch, busy } = useFamily(); const [error, setError] = useState(''); const [color, setColor] = useState(member.color);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { await dispatch({ type: 'member', value: { ...member, name: String(f.get('name')).trim(), color } }); done('Family profile updated.'); } catch (e) { setError((e as Error).message); } }
  return <Panel title="Their little corner" subtitle="A familiar name and a colour of their own." back={close}><form className="form-stack" onSubmit={submit}><Field label="Name"><input name="name" required maxLength={40} defaultValue={member.name}/></Field><fieldset><legend>Profile colour</legend><div className="color-options">{[0, 1, 2, 3, 4].map(c => <button type="button" className={`avatar color-${c}`} aria-label={`Colour ${c + 1}`} aria-pressed={c === color} key={c} onClick={() => setColor(c)}>{c === color && <Check/>}</button>)}</div></fieldset><ErrorMessage message={error}/><Submit busy={busy}>Save profile</Submit></form></Panel>;
}

type Recognition = { lang: string; continuous: boolean; interimResults: boolean; onresult: ((e: { results: ArrayLike<ArrayLike<{ transcript: string }>> }) => void) | null; onerror: ((e: { error: string }) => void) | null; onend: (() => void) | null; start: () => void; stop: () => void };
type SpeechWindow = Window & { SpeechRecognition?: new () => Recognition; webkitSpeechRecognition?: new () => Recognition };
export function CaptureForm({ close, done, mode }: Props & { mode: 'voice' | 'camera' | 'note' }) {
  const { data, dispatch, busy } = useFamily(); const [text, setText] = useState(''); const [photo, setPhoto] = useState(''); const [error, setError] = useState(''); const [listening, setListening] = useState(false); const speech = useRef<Recognition | null>(null); const [reading, setReading] = useState(false);
  const Speech = (window as SpeechWindow).SpeechRecognition ?? (window as SpeechWindow).webkitSpeechRecognition;
  function dictate() { if (!Speech) return; if (listening) { speech.current?.stop(); return; } const r = new Speech(); speech.current = r; r.lang = navigator.language; r.continuous = false; r.interimResults = false; r.onresult = e => setText(t => `${t}${t ? ' ' : ''}${Array.from(e.results).map(x => x[0].transcript).join(' ')}`); r.onerror = e => { setError(`Voice capture stopped (${e.error}). You can type or use your keyboard’s microphone.`); setListening(false); }; r.onend = () => setListening(false); try { r.start(); setListening(true); setError(''); } catch { setError('Voice is unavailable here. Use your keyboard’s microphone to dictate.'); } }
  async function loadPhoto(file?: File) { if (!file) return; if (!file.type.startsWith('image/')) { setError('Choose an image file.'); return; } setReading(true); try { const bitmap = await createImageBitmap(file); const scale = Math.min(1, 1200 / Math.max(bitmap.width, bitmap.height)); const canvas = document.createElement('canvas'); canvas.width = bitmap.width * scale; canvas.height = bitmap.height * scale; canvas.getContext('2d')!.drawImage(bitmap, 0, 0, canvas.width, canvas.height); const encoded = canvas.toDataURL('image/jpeg', 0.72); bitmap.close(); if (encoded.length > 1800000) throw new Error('This photo is too large. Please choose a smaller image.'); setPhoto(encoded); setError(''); } catch (e) { setError((e as Error).message || 'Could not open this photo. Try a JPEG image.'); } finally { setReading(false); } }
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); speech.current?.stop(); const f = new FormData(e.currentTarget); try { await dispatch({ type: 'note', value: { id: uid(), text: text.trim(), memberId: String(f.get('member')), createdAt: new Date().toISOString(), image: photo || undefined } }); done('Note saved. Medicine doses must be logged separately.'); } catch (e) { setError((e as Error).message); } }
  return <Panel title="Catch the little things." subtitle="Save a thought or a medicine-label photo, then come back to it." back={() => { speech.current?.stop(); close(); }}><form onSubmit={submit} className="form-stack"><Field label="For"><select name="member"><option value="">The whole family</option>{data.members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></Field>{mode === 'voice' && <div className="notice">{Speech ? 'Your browser may send speech to its speech service. Start only when you’re ready.' : 'Use the microphone on your phone’s keyboard to dictate into the note below.'}</div>}<Field label="Your note"><textarea value={text} onChange={e => setText(e.target.value)} rows={6} maxLength={3000} placeholder="What would you like to remember?"/></Field><div className="capture-options"><button type="button" className="secondary" disabled={!Speech} onClick={dictate}><Mic size={18}/>{listening ? 'Stop listening' : 'Dictate note'}</button><label className="secondary file-button"><Camera size={18}/>{reading ? 'Opening…' : 'Add photo'}<input type="file" accept="image/*" capture="environment" onChange={e => void loadPhoto(e.target.files?.[0])}/></label></div>{photo && <div className="photo-preview"><img src={photo} alt="Attached note"/><button type="button" className="icon-button" aria-label="Remove photo" onClick={() => setPhoto('')}><Trash2 size={18}/></button></div>}<p className="hint">Notes and photos do not automatically create dose records or schedules. Review the label and use Medicines to add a course.</p><ErrorMessage message={error}/><Submit busy={busy || reading || listening}>Save note</Submit></form></Panel>;
}
