import { describe, it, expect } from 'vitest';
import { addDays, allSlots, applyOperation, dateKey, demoFamily, slotsForCourse } from './domain';
import type { Dose } from './domain';
describe('medicine records', () => {
  it('creates exactly twelve slots for four days at three explicit times', () => { const d = demoFamily(); const slots = allSlots(d); expect(slots).toHaveLength(12); expect(dateKey(slots[11].at)).toBe(addDays(dateKey(), 3)); });
  it('rejects simultaneous duplicate records when a write is replayed', () => { const data = demoFamily(); const dose: Dose = { id: 'a', courseId: 'demo-course', slot: `${dateKey()}T08:00`, actualAt: new Date().toISOString(), recordedAt: new Date().toISOString(), by: 'Dad', amount: 1, unit: 'demo dose', status: 'given', note: '' }; const first = applyOperation(data, { type: 'dose', value: dose }); expect(() => applyOperation(first, { type: 'dose', value: { ...dose, id: 'b', by: 'Mum' } })).toThrow('already been recorded'); });
  it('keeps planned slots unchanged after a late dose and preserves corrected history', () => { const data = demoFamily(); const dose: Dose = { id: 'a', courseId: 'demo-course', slot: `${dateKey()}T08:00`, actualAt: new Date().toISOString(), recordedAt: new Date().toISOString(), by: 'Dad', amount: 1, unit: 'demo dose', status: 'given', note: '' }; let saved = applyOperation(data, { type: 'dose', value: dose }); expect(allSlots(saved)[1].key).toBe(`${dateKey()}T14:00`); saved = applyOperation(saved, { type: 'void', id: 'a', reason: 'Entered against wrong time', at: new Date().toISOString() }); expect(saved.doses[0].voidReason).toBe('Entered against wrong time'); expect(allSlots(saved)[0].record).toBeUndefined(); });
  it('ends reminders when a course is stopped', () => { const d = demoFamily(); const c = { ...d.courses[0], stoppedAt: new Date(`${dateKey()}T15:00`).toISOString() }; expect(slotsForCourse(c, [])).toHaveLength(2); });
  it('rejects duplicate times, invalid dates, zero doses and future records', () => { const d = demoFamily(); const c = { ...d.courses[0], id: 'new' }; expect(() => applyOperation(d, { type: 'course', value: { ...c, times: ['08:00', '08:00'] } })).toThrow(); expect(() => applyOperation(d, { type: 'course', value: { ...c, startDate: '2026-02-30' } })).toThrow(); expect(() => applyOperation(d, { type: 'course', value: { ...c, amount: 0 } })).toThrow(); });
  it('handles year and leap boundaries using calendar days', () => { expect(addDays('2026-12-31', 1)).toBe('2027-01-01'); expect(addDays('2028-02-28', 1)).toBe('2028-02-29'); });
});
